name: mpaswf-bflow
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pyyaml>=6.0
  - numpy>=1.24
  - netcdf4>=1.6
  - cftime>=1.6
  - xarray>=2024.1
  - windspharm>=2.0
  - pyspharm>=1.0.9
  - pip
  - pip:
      - -e .
