from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import netCDF4
import numpy as np


@dataclass(frozen=True)
class EsmfSparseWeights:
    path: Path
    row: np.ndarray
    col: np.ndarray
    weights: np.ndarray
    src_size: int
    dst_size: int
    src_grid_dims: tuple[int, ...]
    dst_grid_dims: tuple[int, ...]


def _read_optional_dims(ds: netCDF4.Dataset, name: str) -> tuple[int, ...]:
    if name not in ds.variables:
        return ()
    values = np.asarray(ds.variables[name][:], dtype="i8").ravel()
    return tuple(int(v) for v in values if int(v) > 0)


def _infer_size(values: np.ndarray, dims: tuple[int, ...]) -> int:
    if dims:
        size = int(np.prod(dims))
        if size > 0:
            return size
    return int(values.max()) + 1 if values.size else 0


def load_esmf_sparse_weights(path: Path) -> EsmfSparseWeights:
    """Load an ESMF sparse weight file generated by ESMF/NCL/xESMF.

    ESMF stores weights in 1-based sparse form using the variables `row`, `col`
    and `S`, where row indexes the destination grid and col indexes the source
    grid. This reader lets BFLOW apply the exact same ESMF weights from Python,
    avoiding an approximation such as nearest-neighbor IDW.
    """
    path = Path(path)
    if not path.exists():
        raise SystemExit(
            f"ERRO: arquivo de pesos ESMF não encontrado: {path}\n"
            "Gere os pesos com ESMF/xESMF uma vez ou copie os pesos já validados "
            "do fluxo NCL para o workspace BFLOW."
        )

    with netCDF4.Dataset(path) as ds:
        missing = [name for name in ("row", "col", "S") if name not in ds.variables]
        if missing:
            raise SystemExit(f"ERRO: arquivo de pesos inválido {path}; variáveis ausentes: {missing}")
        row = np.asarray(ds.variables["row"][:], dtype="i8").ravel() - 1
        col = np.asarray(ds.variables["col"][:], dtype="i8").ravel() - 1
        weights = np.asarray(ds.variables["S"][:], dtype="f8").ravel()
        src_grid_dims = _read_optional_dims(ds, "src_grid_dims")
        dst_grid_dims = _read_optional_dims(ds, "dst_grid_dims")

    if row.size != col.size or row.size != weights.size:
        raise SystemExit(f"ERRO: pesos ESMF inconsistentes em {path}: row/col/S têm tamanhos diferentes")
    if row.size == 0:
        raise SystemExit(f"ERRO: arquivo de pesos ESMF vazio: {path}")
    if row.min() < 0 or col.min() < 0:
        raise SystemExit(f"ERRO: arquivo de pesos ESMF usa índices inválidos: {path}")

    return EsmfSparseWeights(
        path=path,
        row=row,
        col=col,
        weights=weights,
        src_size=_infer_size(col, src_grid_dims),
        dst_size=_infer_size(row, dst_grid_dims),
        src_grid_dims=src_grid_dims,
        dst_grid_dims=dst_grid_dims,
    )


def apply_esmf_weights(values: np.ndarray, weights: EsmfSparseWeights) -> np.ndarray:
    """Apply ESMF sparse weights to arrays shaped `(nlev, nsource)`.

    The returned array has shape `(nlev, ndestination)`.
    """
    values = np.asarray(values)
    if values.ndim != 2:
        raise ValueError(f"values deve ter shape (nlev, nsource); recebido {values.shape}")
    if values.shape[1] < weights.src_size:
        raise SystemExit(
            f"ERRO: pesos {weights.path} esperam pelo menos {weights.src_size} pontos de origem, "
            f"mas a variável tem {values.shape[1]}."
        )
    out = np.zeros((values.shape[0], weights.dst_size), dtype="f8")
    for level in range(values.shape[0]):
        np.add.at(out[level], weights.row, values[level, weights.col] * weights.weights)
    return out


def latlon_shape_from_weights(weights: EsmfSparseWeights) -> tuple[int, int]:
    """Infer `(nlat, nlon)` from an ESMF regular lat/lon destination/source grid."""
    dims = weights.dst_grid_dims or weights.src_grid_dims
    if len(dims) >= 2:
        # ESMF/NCL commonly stores regular grids as (nlon, nlat).
        nlon, nlat = int(dims[0]), int(dims[1])
        return nlat, nlon
    if weights.dst_size == 180 * 360 or weights.src_size == 180 * 360:
        return 180, 360
    raise SystemExit(
        f"ERRO: não foi possível inferir shape lat/lon para pesos {weights.path}. "
        "Esperado dst_grid_dims/src_grid_dims ou grade 180x360."
    )


def weight_paths(config, workspace: Path) -> tuple[Path, Path]:
    mesh_name = config["mesh"]["name"]
    weight_dir = Path(workspace) / "ESMF_weights"
    mpas_to_latlon = weight_dir / f"MPAS_{mesh_name}_to_latlon_1p0_bilinear.nc"
    latlon_to_mpas = weight_dir / f"latlon_1p0_to_MPAS_{mesh_name}_bilinear.nc"
    return mpas_to_latlon, latlon_to_mpas


def ensure_esmf_weights(config, workspace: Path) -> tuple[Path, Path]:
    """Validate that the ESMF weight files expected by BFLOW are available.

    The actual generation can be done by xESMF/ESMF or reused from the old NCL
    workflow. This function intentionally does not generate approximate weights.
    """
    mpas_to_latlon, latlon_to_mpas = weight_paths(config, workspace)
    missing = [str(path) for path in (mpas_to_latlon, latlon_to_mpas) if not path.exists()]
    if missing:
        raise SystemExit(
            "ERRO: pesos ESMF não encontrados no workspace BFLOW:\n"
            + "\n".join(missing)
            + "\n\nGere os pesos uma vez com ESMF/xESMF ou copie os arquivos já validados para "
            + str(Path(workspace) / "ESMF_weights")
            + "."
        )
    return mpas_to_latlon, latlon_to_mpas


def generate_esmf_weights(config, workspace: Path) -> None:
    """Compatibility hook used by the runner.

    In the pure-Python BFLOW pipeline, this step validates and reuses existing
    ESMF sparse weight files instead of generating NCL scripts. The interpolation
    itself is performed by :func:`apply_esmf_weights` in Python.
    """
    mpas_to_latlon, latlon_to_mpas = ensure_esmf_weights(config, workspace)
    print(f"Using ESMF weights: {mpas_to_latlon}")
    print(f"Using ESMF weights: {latlon_to_mpas}")
