from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import os
import shlex
import subprocess
import tempfile

import netCDF4
import numpy as np


@dataclass(frozen=True)
class EsmfSparseWeights:
    path: Path
    row: np.ndarray
    col: np.ndarray
    weights: np.ndarray
    src_size: int
    dst_size: int
    src_grid_dims: tuple[int, ...]
    dst_grid_dims: tuple[int, ...]


def _read_optional_dims(ds: netCDF4.Dataset, name: str) -> tuple[int, ...]:
    if name not in ds.variables:
        return ()
    values = np.asarray(ds.variables[name][:], dtype="i8").ravel()
    return tuple(int(v) for v in values if int(v) > 0)


def _infer_size(values: np.ndarray, dims: tuple[int, ...]) -> int:
    if dims:
        size = int(np.prod(dims))
        if size > 0:
            return size
    return int(values.max()) + 1 if values.size else 0


def _validate_sparse_weight_file(path: Path) -> None:
    if not path.exists():
        raise SystemExit(f"ERRO: arquivo de pesos ESMF não encontrado: {path}")
    try:
        with netCDF4.Dataset(path) as ds:
            missing = [name for name in ("row", "col", "S") if name not in ds.variables]
            if missing:
                raise SystemExit(f"ERRO: arquivo de pesos inválido {path}; variáveis ausentes: {missing}")
            sizes = [int(ds.variables[name].size) for name in ("row", "col", "S")]
    except OSError as exc:
        raise SystemExit(f"ERRO: não foi possível abrir o arquivo de pesos ESMF {path}: {exc}") from exc
    if not all(sizes):
        raise SystemExit(f"ERRO: arquivo de pesos ESMF vazio: {path}")
    if len(set(sizes)) != 1:
        raise SystemExit(f"ERRO: pesos ESMF inconsistentes em {path}: row/col/S têm tamanhos diferentes")


def load_esmf_sparse_weights(path: Path) -> EsmfSparseWeights:
    """Load an ESMF sparse weight file generated by ESMF/NCL/xESMF.

    ESMF stores weights in 1-based sparse form using the variables ``row``, ``col``
    and ``S``, where row indexes the destination grid and col indexes the source
    grid. This reader lets BFLOW apply the exact same ESMF weights from Python,
    avoiding an approximation such as nearest-neighbor IDW.
    """
    path = Path(path)
    _validate_sparse_weight_file(path)

    with netCDF4.Dataset(path) as ds:
        row = np.asarray(ds.variables["row"][:], dtype="i8").ravel() - 1
        col = np.asarray(ds.variables["col"][:], dtype="i8").ravel() - 1
        weights = np.asarray(ds.variables["S"][:], dtype="f8").ravel()
        src_grid_dims = _read_optional_dims(ds, "src_grid_dims")
        dst_grid_dims = _read_optional_dims(ds, "dst_grid_dims")

    if row.min() < 0 or col.min() < 0:
        raise SystemExit(f"ERRO: arquivo de pesos ESMF usa índices inválidos: {path}")

    return EsmfSparseWeights(
        path=path,
        row=row,
        col=col,
        weights=weights,
        src_size=_infer_size(col, src_grid_dims),
        dst_size=_infer_size(row, dst_grid_dims),
        src_grid_dims=src_grid_dims,
        dst_grid_dims=dst_grid_dims,
    )


def apply_esmf_weights(values: np.ndarray, weights: EsmfSparseWeights) -> np.ndarray:
    """Apply ESMF sparse weights to arrays shaped ``(nlev, nsource)``.

    The returned array has shape ``(nlev, ndestination)``.
    """
    values = np.asarray(values)
    if values.ndim != 2:
        raise ValueError(f"values deve ter shape (nlev, nsource); recebido {values.shape}")
    if values.shape[1] < weights.src_size:
        raise SystemExit(
            f"ERRO: pesos {weights.path} esperam pelo menos {weights.src_size} pontos de origem, "
            f"mas a variável tem {values.shape[1]}."
        )
    out = np.zeros((values.shape[0], weights.dst_size), dtype="f8")
    for level in range(values.shape[0]):
        np.add.at(out[level], weights.row, values[level, weights.col] * weights.weights)
    return out


def latlon_shape_from_weights(weights: EsmfSparseWeights) -> tuple[int, int]:
    """Infer ``(nlat, nlon)`` from an ESMF regular lat/lon destination/source grid."""
    dims = weights.dst_grid_dims or weights.src_grid_dims
    if len(dims) >= 2:
        # ESMF/NCL commonly stores regular grids as (nlon, nlat).
        nlon, nlat = int(dims[0]), int(dims[1])
        return nlat, nlon
    if weights.dst_size == 180 * 360 or weights.src_size == 180 * 360:
        return 180, 360
    raise SystemExit(
        f"ERRO: não foi possível inferir shape lat/lon para pesos {weights.path}. "
        "Esperado dst_grid_dims/src_grid_dims ou grade 180x360."
    )


def _regridding_config(config) -> dict:
    bflow = config.get("bflow") if isinstance(config, dict) else None
    regridding = bflow.get("regridding") if isinstance(bflow, dict) else None
    if not isinstance(regridding, dict):
        raise SystemExit(
            "ERRO: configuração bflow.regridding não encontrada. "
            "Verifique bmatrix.configuration no YAML de plataforma."
        )
    return regridding


def _render(value, key: str, config) -> str:
    if not isinstance(value, str) or not value:
        raise SystemExit(f"ERRO: bflow.regridding.{key} deve ser uma string não vazia.")
    mesh_name = config["mesh"]["name"]
    try:
        return value.format(mesh_name=mesh_name)
    except KeyError as exc:
        raise SystemExit(
            f"ERRO: placeholder desconhecido em bflow.regridding.{key}: {exc}. "
            "Use somente valores definidos, como {mesh_name}."
        ) from exc


def _workspace_path(workspace: Path, value: str) -> Path:
    path = Path(value)
    return path if path.is_absolute() else Path(workspace) / path


def _artifact_path(directory: Path, value: str) -> Path:
    path = Path(value)
    return path if path.is_absolute() else directory / path


def weight_paths(config, workspace: Path) -> tuple[Path, Path]:
    """Resolve the two ESMF files exclusively from ``bflow.regridding``."""
    regridding = _regridding_config(config)
    directory = _workspace_path(
        workspace,
        _render(regridding.get("weights_directory", "ESMF_weights"), "weights_directory", config),
    )
    mpas_to_latlon = _artifact_path(
        directory,
        _render(regridding.get("weight_mpas_to_latlon"), "weight_mpas_to_latlon", config),
    )
    latlon_to_mpas = _artifact_path(
        directory,
        _render(regridding.get("weight_latlon_to_mpas"), "weight_latlon_to_mpas", config),
    )
    return mpas_to_latlon, latlon_to_mpas


def ensure_esmf_weights(config, workspace: Path) -> tuple[Path, Path]:
    """Validate that the ESMF weight files expected by BFLOW are available."""
    mpas_to_latlon, latlon_to_mpas = weight_paths(config, workspace)
    missing = [str(path) for path in (mpas_to_latlon, latlon_to_mpas) if not path.exists()]
    if missing:
        raise SystemExit(
            "ERRO: pesos ESMF não encontrados após a preparação BFLOW:\n"
            + "\n".join(missing)
            + "\n\nExecute sem --skip-weights para permitir a geração automática ou "
            "disponibilize pesos válidos nos caminhos configurados."
        )
    _validate_sparse_weight_file(mpas_to_latlon)
    _validate_sparse_weight_file(latlon_to_mpas)
    return mpas_to_latlon, latlon_to_mpas


def _ncl_string(value: str | Path) -> str:
    return str(value).replace("\\", "\\\\").replace('"', '\\"')


def _ncl_bool(value: bool) -> str:
    return "True" if value else "False"


def _generation_settings(config, regridding: dict) -> tuple[str, str]:
    generation = regridding.get("weight_generation", {})
    if generation is None:
        generation = {}
    if not isinstance(generation, dict):
        raise SystemExit("ERRO: bflow.regridding.weight_generation deve ser um mapa.")

    backend = generation.get("backend", "ncl")
    if backend != "ncl":
        raise SystemExit(
            f"ERRO: backend de geração de pesos não suportado: {backend!r}. "
            "O backend disponível é 'ncl', que usa as rotinas ESMF do NCL."
        )
    command = generation.get("command", "ncl")
    if not isinstance(command, str) or not command:
        raise SystemExit("ERRO: bflow.regridding.weight_generation.command deve ser uma string não vazia.")
    module_load = generation.get("module_load", regridding.get("ncl_module_load", regridding.get("module_load", "")))
    if not isinstance(module_load, str):
        raise SystemExit("ERRO: módulo de geração ESMF/NCL deve ser uma string.")
    return command, module_load


def _link_mpas_grid(invariant: Path, mpas_grid: Path) -> None:
    if not invariant.exists():
        raise SystemExit(f"ERRO: arquivo MPAS para geração dos pesos não encontrado: {invariant}")
    mpas_grid.parent.mkdir(parents=True, exist_ok=True)
    if mpas_grid.is_symlink() or mpas_grid.exists():
        if mpas_grid.is_symlink() and mpas_grid.resolve() == invariant.resolve():
            return
        mpas_grid.unlink()
    os.symlink(invariant, mpas_grid)


def _ncl_weight_script(
    invariant_grid: Path,
    mpas_grid: Path,
    scrip_grid: Path,
    esmf_grid: Path,
    latlon_to_mpas: Path,
    mpas_to_latlon: Path,
    regridding: dict,
    generate_latlon_to_mpas: bool,
    generate_mpas_to_latlon: bool,
) -> str:
    lower_left = regridding.get("lower_left")
    upper_right = regridding.get("upper_right")
    if not isinstance(lower_left, list) or len(lower_left) != 2:
        raise SystemExit("ERRO: bflow.regridding.lower_left deve ser [latitude, longitude].")
    if not isinstance(upper_right, list) or len(upper_right) != 2:
        raise SystemExit("ERRO: bflow.regridding.upper_right deve ser [latitude, longitude].")

    interpolation_method = regridding.get("interpolation_method")
    resolution = regridding.get("scrip_resolution")
    if not isinstance(interpolation_method, str) or not interpolation_method:
        raise SystemExit("ERRO: bflow.regridding.interpolation_method deve ser uma string não vazia.")
    if not isinstance(resolution, str) or not resolution:
        raise SystemExit("ERRO: bflow.regridding.scrip_resolution deve ser uma string não vazia.")

    title = str(regridding.get("title", "Configured latitude-longitude grid"))
    precision_probe = str(regridding.get("precision_probe_variable", "latCell"))
    lower_lat, lower_lon = lower_left
    upper_lat, upper_lon = upper_right

    return f'''load "$NCARG_ROOT/lib/ncarg/nclscripts/esmf/ESMF_regridding.ncl"

begin
  dstFileName = "{_ncl_string(mpas_grid)}"
  interpMethod = "{_ncl_string(interpolation_method)}"
  srcGridName = "{_ncl_string(scrip_grid)}"
  dstGridName = "{_ncl_string(esmf_grid)}"
  wgtFile1 = "{_ncl_string(latlon_to_mpas)}"
  wgtFile2 = "{_ncl_string(mpas_to_latlon)}"

  SKIP_TRI_SCRIP_GEN = False
  SKIP_MPAS_ESMF_GEN = False
  SKIP_WGT_GEN_1 = {_ncl_bool(not generate_latlon_to_mpas)}
  SKIP_WGT_GEN_2 = {_ncl_bool(not generate_mpas_to_latlon)}

  if(.not.SKIP_TRI_SCRIP_GEN) then
    Opt = True
    Opt@ForceOverwrite = True
    Opt@PrintTimings = True
    Opt@LLCorner = (/ {lower_lat}d0, {lower_lon}d0 /)
    Opt@URCorner = (/ {upper_lat}d0, {upper_lon}d0 /)
    Opt@Title = "{_ncl_string(title)}"
    latlon_to_SCRIP(srcGridName, "{_ncl_string(resolution)}", Opt)
    delete(Opt)
  end if

  dfile = addfile(dstFileName, "r")
  r2d = 180.0/(atan(1)*4.0)
  lonCell = dfile->lonCell*r2d
  latCell = dfile->latCell*r2d

  if(.not.SKIP_MPAS_ESMF_GEN) then
    Opt = True
    Opt@ForceOverwrite = True
    Opt@PrintTimings = True
    Opt@InputFileName = dstFileName
    unstructured_to_ESMF(dstGridName, latCell, lonCell, Opt)
    delete(Opt)
  end if

  if(.not.SKIP_WGT_GEN_1) then
    Opt = True
    Opt@InterpMethod = interpMethod
    Opt@SrcESMF = False
    Opt@DstESMF = True
    Opt@ForceOverwrite = True
    Opt@PrintTimings = True
    Opt@Debug = True
    Opt@Check = True
    Opt@DstGridType = "unstructured"
    ESMF_regrid_gen_weights(srcGridName, dstGridName, wgtFile1, Opt)
    delete(Opt)
  end if

  if(.not.SKIP_WGT_GEN_2) then
    Opt = True
    Opt@InterpMethod = interpMethod
    Opt@SrcESMF = True
    Opt@DstESMF = False
    Opt@ForceOverwrite = True
    Opt@PrintTimings = True
    Opt@Debug = True
    Opt@Check = True
    Opt@DstGridType = "unstructured"
    ESMF_regrid_gen_weights(dstGridName, srcGridName, wgtFile2, Opt)
    delete(Opt)
  end if
end
'''


def _generate_missing_weights_with_ncl(config, workspace: Path, missing: set[Path]) -> None:
    regridding = _regridding_config(config)
    mpas_to_latlon, latlon_to_mpas = weight_paths(config, workspace)
    weight_dir = mpas_to_latlon.parent
    if latlon_to_mpas.parent != weight_dir:
        raise SystemExit(
            "ERRO: os dois arquivos de pesos devem usar o mesmo diretório para a geração automática."
        )
    weight_dir.mkdir(parents=True, exist_ok=True)

    mpas_grid = _artifact_path(weight_dir, _render(regridding.get("mpas_grid_file"), "mpas_grid_file", config))
    scrip_grid = _artifact_path(weight_dir, _render(regridding.get("scrip_grid_file"), "scrip_grid_file", config))
    esmf_grid = _artifact_path(weight_dir, _render(regridding.get("esmf_grid_file"), "esmf_grid_file", config))
    invariant = Path(config["static"]["invariant"])
    _link_mpas_grid(invariant, mpas_grid)

    command, module_load = _generation_settings(config, regridding)
    script = _ncl_weight_script(
        invariant,
        mpas_grid,
        scrip_grid,
        esmf_grid,
        latlon_to_mpas,
        mpas_to_latlon,
        regridding,
        generate_latlon_to_mpas=latlon_to_mpas in missing,
        generate_mpas_to_latlon=mpas_to_latlon in missing,
    )
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".ncl", prefix="generate_esmf_weights_", dir=weight_dir, delete=False, encoding="utf-8"
    ) as handle:
        handle.write(script)
        script_path = Path(handle.name)

    try:
        shell_command = "\n".join(
            [
                "set -euo pipefail",
                module_load,
                f"cd {shlex.quote(str(weight_dir))}",
                f"{command} {shlex.quote(str(script_path))} < /dev/null",
            ]
        )
        result = subprocess.run(["bash", "-lc", shell_command], check=False)
        if result.returncode != 0:
            raise SystemExit(
                "ERRO: a geração ESMF dos pesos falhou "
                f"(código de saída {result.returncode}). Veja a saída acima."
            )
    finally:
        script_path.unlink(missing_ok=True)


def generate_esmf_weights(config, workspace: Path) -> None:
    """Reuse validated ESMF weights or generate only the missing ones.

    The Python pipeline owns orchestration and validation.  When needed, it invokes
    the NCL ESMF routines configured in ``bflow.regridding.weight_generation``;
    this preserves the same ESMF interpolation construction used by the validated
    legacy BFLOW while avoiding persistent generated helper scripts.
    """
    mpas_to_latlon, latlon_to_mpas = weight_paths(config, workspace)
    expected = (mpas_to_latlon, latlon_to_mpas)
    missing = {path for path in expected if not path.exists()}
    if missing:
        print("Generating missing ESMF weights")
        for path in sorted(missing):
            print(f"  missing: {path}")
        _generate_missing_weights_with_ncl(config, Path(workspace), missing)
    else:
        print("Reusing existing ESMF weights")

    mpas_to_latlon, latlon_to_mpas = ensure_esmf_weights(config, workspace)
    print(f"Using ESMF weights: {mpas_to_latlon}")
    print(f"Using ESMF weights: {latlon_to_mpas}")
