from __future__ import annotations

from pathlib import Path

from ..shell import require_file, symlink_force, write_text
from .manifest import write_manifest
from .model import BflowPair, compact_time


def validate_pairs(pairs: list[BflowPair]) -> None:
    if not pairs:
        raise SystemExit("ERRO: nenhum par Bflow encontrado.")
    for pair in pairs:
        require_file(pair.f048, f"f048 para {pair.valid_time}")
        require_file(pair.f024, f"f024 para {pair.valid_time}")


def link_pair_inputs(workspace: Path, pairs: list[BflowPair]) -> None:
    inputs = workspace / "inputs"
    for pair in pairs:
        vdir = inputs / compact_time(pair.valid_time)
        symlink_force(pair.f048, vdir / "f048.nc")
        symlink_force(pair.f024, vdir / "f024.nc")
        write_text(vdir / "pair.env", f"VALID_TIME={pair.valid_time}\nF048={pair.f048}\nF024={pair.f024}\n")


def write_readme(workspace: Path, pairs: list[BflowPair]) -> None:
    lines = [
        "# Bflow preprocessing workspace",
        "",
        "Generated by `mpasbflow prepare` or `mpasbflow all`.",
        "",
        "## Inputs",
        "",
    ]
    for pair in pairs:
        lines.extend([f"- `{pair.valid_time}`", f"  - f048: `{pair.f048}`", f"  - f024: `{pair.f024}`"])
    lines.extend(
        [
            "",
            "## Run",
            "",
            "```bash",
            "mpasbflow run --workspace $(pwd) --clean-output",
            "```",
            "",
            "Products are written below `output/YYYYMMDDHH/`.",
            "The current Python runner no longer generates Python helper scripts or a master shell script.",
        ]
    )
    write_text(workspace / "README.md", "\n".join(lines) + "\n")


def prepare_workspace(config, pairs: list[BflowPair], workspace: Path, force: bool = False) -> Path:
    workspace.mkdir(parents=True, exist_ok=True)
    (workspace / "scripts").mkdir(exist_ok=True)
    (workspace / "logs").mkdir(exist_ok=True)
    (workspace / "output").mkdir(exist_ok=True)

    validate_pairs(pairs)
    write_manifest(workspace / "manifest.tsv", pairs)
    link_pair_inputs(workspace, pairs)
    write_readme(workspace, pairs)
    return workspace
