stages:
  forecast:
    streams:
      template: "{atmosphere_share}/streams.atmosphere"
      output: streams.atmosphere
      streams:
        invariant:
          attributes:
            type: input
            input_interval: initial_only
            filename_template: "{static_output_name}"
        input:
          attributes:
            type: input
            input_interval: initial_only
            filename_template: "{init_output_name}"
        surface:
          attributes:
            filename_template: "{surface_update_output_name}"
        ugwp_oro_data_in:
          attributes:
            filename_template: "{ugwp_oro_output_name}"
        restart:
          tag: stream
          attributes:
            type: output
            filename_template: "{restart_filename}"
            filename_interval: output_interval
            output_interval: "{output_interval}"
            clobber_mode: overwrite
