stages:
  forecast:
    output_dir: "{render_root}/forecast/{safe_time}/f{lead_hours:03d}_dt{dt}_np{nproc}"
    namelist:
      template: "{atmosphere_share}/namelist.atmosphere"
      output: namelist.atmosphere
      groups:
        nhyd_model:
          config_dt: "{dt}.0"
          config_start_time: "'{init_time}'"
          config_run_duration: "'{run_duration}'"
          config_len_disp: "240000.0"
        restart:
          config_do_restart: false
        decomposition:
          config_block_decomp_file_prefix: "'{graph_basename}.part.'"
        damping:
          config_epssm_minimum: "0.1"
          config_epssm_maximum: "0.5"
          config_epssm_transition_bottom_z: "30000."
          config_epssm_transition_top_z: "50000."
