stages:
  static:
    output_dir: "{render_root}/static"
    namelist:
      template: "{init_share}/namelist.init_atmosphere"
      output: namelist.init_atmosphere
      groups:
        nhyd_model:
          config_init_case: 7
          config_start_time: "'{init_time}'"
          config_stop_time: "'{init_time}'"
        dimensions:
          config_nvertlevels: "{nvertlevels}"
        decomposition:
          config_block_decomp_file_prefix: "'{graph_basename}.part.'"
        data_sources:
          config_geog_data_path: "'{wps_geog_data_path}/'"
        preproc_stages:
          config_static_interp: true
          config_native_gwd_static: true
          config_native_gwd_gsl_static: false
          config_vertical_grid: false
          config_met_interp: false
    streams:
      template: "{init_share}/streams.init_atmosphere"
      output: streams.init_atmosphere
      streams:
        input:
          attributes:
            type: input
            input_interval: initial_only
            filename_template: "{grid_local_name}"
        output:
          attributes:
            type: output
            filename_template: "{static_output_name}"
            clobber_mode: overwrite
        ugwp_oro_data:
          attributes:
            filename_template: "{ugwp_oro_output_name}"
        surface:
          attributes:
            filename_template: "{surface_update_output_name}"
