schema: workflow-site/v1

site:
  name: jaci
  scheduler: pbs

context:
  project_root: "/p/projetos/monan_das/$USER"
  workspace_root: "{project_root}/work"
  data_workspace_root: "{project_root}/data"
  mesh_catalog_root: "{project_root}/projects/mpas_meshes/quasi_uniform"
  mpas_install_root: "{project_root}/builds/monan-jedi-mpas"
  init_share: "{mpas_install_root}/share/MPAS/core_init_atmosphere"
  atmosphere_share: "{mpas_install_root}/share/MPAS/core_atmosphere"
  mpas_init_executable: "{mpas_install_root}/bin/mpas_init_atmosphere"
  mpas_atmosphere_executable: "{mpas_install_root}/bin/mpas_atmosphere"
  wps_geog_data_path: "{data_workspace_root}/mpas-bmatrix-global/external/WPS_GEOG/low_res_mandatory/WPS_GEOG_LOW_RES"
