includes:
  - ../../sites/jaci.yaml
  - ../default/common.yaml
  - ../default/static.yaml
  - ../default/init.yaml
  - ../default/forecast.yaml

case:
  name: global-x1.10242
  description: Global quasi-uniform MPAS-Atmosphere case at approximately 240 km

# Values a user normally changes when creating another MPAS case.
context:
  mesh_name: x1.10242
  mesh_resolution_km: 240
  nproc: 128
  nvertlevels: 55
  output_interval: "06:00:00"
